export enum COMMISSIONS {
  STANDARD_COMMISSION = "STANDARD",
  STRAIGHT_COMMISSION = "STRAIGHT",
  GOAL_AVERAGE_COMMISSION = "GOAL_AVERAGE",
  GOAL_DEVICE_COMMISSION = "GOAL_DEVICE",
  WINNER_SALE_COMMISSION = "WINNER_SALE_COMMISSION",
}

export enum COMMISSION_OR_EXPENSES {
  STANDARD_COMMISSION = "STANDARD",
  STRAIGHT_COMMISSION = "STRAIGHT",
  GOAL_AVERAGE_COMMISSION = "GOAL_AVERAGE",
  GOAL_DEVICE_COMMISSION = "GOAL_DEVICE",
  GOAL_COMMISSION = "GOAL_COMMISSION",
  WINNER_SALE_COMMISSION = "WINNER_SALE_COMMISSION",
  WINNER_EXPENSE_SALE = "WINNER_EXPENSE_SALE",
  BORROW_EXPENSE_SALE = "BORROW_EXPENSE_SALE",
  COMMITTEE_EXPENSE_SALE = "COMMITTEE_EXPENSE_SALE",
  WINNER_EXPENSE_LAST_DIGIT_SALE = "WINNER_EXPENSE_LAST_DIGIT_SALE",
  VAT_EXPENSE_SALE = "VAT_EXPENSE_SALE",
  OTHER_EXPENSE_SALE = "OTHER_EXPENSE_SALE",
  TOPUP_CARD = "TOPUP_CARD",
}
